/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	autoscalingv1 "k8s.io/api/autoscaling/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1beta1 "knative.dev/eventing-natss/pkg/apis/sources/v1beta1"
)

// FakeNatssSources implements NatssSourceInterface
type FakeNatssSources struct {
	Fake *FakeSourcesV1beta1
	ns   string
}

var natsssourcesResource = schema.GroupVersionResource{Group: "sources", Version: "v1beta1", Resource: "natsssources"}

var natsssourcesKind = schema.GroupVersionKind{Group: "sources", Version: "v1beta1", Kind: "NatssSource"}

// Get takes name of the natssSource, and returns the corresponding natssSource object, and an error if there is any.
func (c *FakeNatssSources) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.NatssSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(natsssourcesResource, c.ns, name), &v1beta1.NatssSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.NatssSource), err
}

// List takes label and field selectors, and returns the list of NatssSources that match those selectors.
func (c *FakeNatssSources) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.NatssSourceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(natsssourcesResource, natsssourcesKind, c.ns, opts), &v1beta1.NatssSourceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.NatssSourceList{ListMeta: obj.(*v1beta1.NatssSourceList).ListMeta}
	for _, item := range obj.(*v1beta1.NatssSourceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested natssSources.
func (c *FakeNatssSources) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(natsssourcesResource, c.ns, opts))

}

// Create takes the representation of a natssSource and creates it.  Returns the server's representation of the natssSource, and an error, if there is any.
func (c *FakeNatssSources) Create(ctx context.Context, natssSource *v1beta1.NatssSource, opts v1.CreateOptions) (result *v1beta1.NatssSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(natsssourcesResource, c.ns, natssSource), &v1beta1.NatssSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.NatssSource), err
}

// Update takes the representation of a natssSource and updates it. Returns the server's representation of the natssSource, and an error, if there is any.
func (c *FakeNatssSources) Update(ctx context.Context, natssSource *v1beta1.NatssSource, opts v1.UpdateOptions) (result *v1beta1.NatssSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(natsssourcesResource, c.ns, natssSource), &v1beta1.NatssSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.NatssSource), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeNatssSources) UpdateStatus(ctx context.Context, natssSource *v1beta1.NatssSource, opts v1.UpdateOptions) (*v1beta1.NatssSource, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(natsssourcesResource, "status", c.ns, natssSource), &v1beta1.NatssSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.NatssSource), err
}

// Delete takes name of the natssSource and deletes it. Returns an error if one occurs.
func (c *FakeNatssSources) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(natsssourcesResource, c.ns, name), &v1beta1.NatssSource{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNatssSources) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(natsssourcesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.NatssSourceList{})
	return err
}

// Patch applies the patch and returns the patched natssSource.
func (c *FakeNatssSources) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.NatssSource, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(natsssourcesResource, c.ns, name, pt, data, subresources...), &v1beta1.NatssSource{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.NatssSource), err
}

// GetScale takes name of the natssSource, and returns the corresponding scale object, and an error if there is any.
func (c *FakeNatssSources) GetScale(ctx context.Context, natssSourceName string, options v1.GetOptions) (result *autoscalingv1.Scale, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetSubresourceAction(natsssourcesResource, c.ns, "scale", natssSourceName), &autoscalingv1.Scale{})

	if obj == nil {
		return nil, err
	}
	return obj.(*autoscalingv1.Scale), err
}
